import React from 'react'
import './pol.css'
import { useEffect } from 'react'

const Policy = () => {

  useEffect(() => {
    window.scrollTo(0, 0)
  }, [])

  useEffect(() => {
    document.title = 'Edu Learning Policy | Terms & conditions'
  })

  return (
    <div className='maro'>
      <h2>PRIVACY POLICY</h2>
      <p><strong>Sistema De Gestion Educativa</strong>(la “Compañía”) se compromete a proteger la privacidad de sus usuarios. Esta Política de Privacidad (“Política de Privacidad”) está diseñada para ayudarlo a comprender qué información recopilamos, cómo la usamos, qué hacemos para protegerla y para ayudarlo a tomar decisiones informadas al utilizar nuestro sitio web. A menos que se indique lo contrario a continuación, esta Política de Privacidad se aplica a cualquier sitio web que haga referencia a esta Política de Privacidad, a cualquier sitio web de la Compañía, así como a cualquier dato que la Compañía pueda recopilar en sitios asociados y no afiliados.</p>
      <p>A los efectos de este Acuerdo, los términos "nosotros", "nos" y "nuestro" se refieren a la Compañía. “Usted” se refiere a usted, como usuario del sitio web. </p>
      <h2>I. CONSIENTO</h2>
      <p>Al acceder a nuestro sitio web, acepta nuestra Política de privacidad y Términos de uso, y acepta nuestra recopilación, almacenamiento, uso y divulgación de su información personal como se describe en esta Política de privacidad. Además, al utilizar nuestro sitio web o los servicios de sitios asociados y no afiliados, usted acepta las políticas y prácticas descritas en esta Política de Privacidad. Cada vez que visita nuestro sitio web, y cada vez que nos proporciona información voluntariamente, acepta que acepta nuestra recopilación, uso y divulgación de la información que proporciona, y acepta recibir correos electrónicos o ser contactado de otro modo, como descrito en esta Política de Privacidad. Ya sea que se registre o no haga algún tipo de negocio con nosotros, esta Política de Privacidad se aplica a todos los usuarios del sitio web..</p>
      <h2>II. INFORMACIÓN QUE RECOPILAMOS</h2>
      <p>Podemos recopilar tanto “Información no personal” como “Información personal” sobre usted. La “Información no personal” incluye información que no se puede utilizar para identificarlo personalmente, como datos de uso anónimos, información demográfica general que podemos recopilar, páginas y URL de referencia/salida, tipos de plataforma, preferencias que usted envía y preferencias que se generan en función de los datos que envía y el número de clics. La “Información personal” incluye información que puede usarse para identificarlo personalmente, como su nombre, dirección y dirección de correo electrónico.</p>
      <h3>Google Analytics</h3>
      <p>Este sitio web utiliza Google Analytics para rastrear información sobre su uso del sitio web. Podemos rastrear la información que nos proporciona su navegador o el uso del sitio web, como el sitio web desde el que procede (conocido como "URL de referencia"), el tipo de navegador que utiliza, el dispositivo desde el que se conectó al sitio web, la hora y fecha de acceso, y otra información que no lo identifica personalmente. Utilizamos esta información, entre otras cosas, para el funcionamiento del sitio web, para mantener la calidad del sitio web, para proporcionar estadísticas generales sobre el uso del sitio web y para otros fines comerciales. </p>
      <h3>Cookies</h3>
      <p>Realizamos un seguimiento de esta información en Google Analytics mediante cookies o pequeños archivos de texto que incluyen un identificador único anónimo. Las cookies se envían al navegador de un usuario desde nuestros servidores y se almacenan en el disco duro de la computadora del usuario. Enviar una cookie al navegador de un usuario nos permite recopilar información no personal sobre ese usuario y mantener un registro de las preferencias del usuario al utilizar nuestros servicios, tanto de forma individual como agregada. La Compañía puede utilizar cookies tanto persistentes como de sesión; Las cookies persistentes permanecen en su computadora después de que cierra su sesión y hasta que las elimina, mientras que las cookies de sesión caducan cuando cierra su navegador. Las cookies persistentes se pueden eliminar siguiendo las instrucciones del archivo de ayuda de su navegador de Internet. Si elige desactivar las cookies, es posible que algunas áreas del sitio web no funcionen correctamente.</p>
      <ul><li><strong>Puede desactivar las cookies en su navegador siguiendo las siguientes instrucciones:</strong></li></ul>
      <ul><li><a href="https://support.microsoft.com/en-us/help/17442/windows-internet-explorer-delete-manage-cookies" target="_blank" rel="noreferrer">Internet Explorer</a></li>
        <li><a href="https://support.google.com/accounts/answer/61416" target="_blank" rel="noreferrer">Chrome</a></li>
        <li><a href="https://support.mozilla.org/en-US/kb/enable-and-disable-cookies-website-preferences" target="_blank" rel="noreferrer">Firefox</a></li>
        <li><a href="https://support.apple.com/guide/safari/manage-cookies-and-website-data-sfri11471/mac" target="_blank" rel="noreferrer">Safari</a></li>
        <li>Para cualquier otro navegador, por favor consulte directamente la información de ayuda para la gestión de cookies disponible en Internet.</li></ul>
      <h3>Website Forms</h3>
      <p>Es posible que haya varios formularios en línea en nuestro sitio web donde puede enviar información de identificación personal para expresar interés en nuestro negocio o enviar una consulta sobre nuestro negocio. Estos formularios pueden aparecer como formularios RFP, formularios de Contáctenos, formularios RFP para bodas u otros formularios similares que solicitan su información antes de enviarlos. Cuando se comunica con nosotros mediante un formulario en nuestro sitio web, recopilamos información que lo identifica, como su nombre, cargo, nombre comercial, número de teléfono, dirección de correo electrónico y otra información de identificación personal. Parte de esta información es obligatoria y otra información es opcional. Esta información se utiliza para abordar mejor su consulta y no se utiliza con fines de marketing ni se comparte con otras empresas de terceros. Si prefiere que no recopilemos esta información, simplemente no complete el formulario. Si ya envió su información a través de un formulario y desea ser eliminado, envíenos un correo electrónico.</p>
      <h3>Email Communications</h3>
      <p>Según la información personal que nos proporciona, podemos comunicarnos con usted en respuesta a sus consultas para brindarle los servicios que solicita y administrar su cuenta. Nos comunicaremos con usted por correo electrónico o por teléfono, de acuerdo con sus deseos. También podemos utilizar su información personal para enviarle actualizaciones y otras comunicaciones promocionales. Si ya no desea recibir esas actualizaciones por correo electrónico, puede optar por no recibirlas siguiendo las instrucciones incluidas en cada actualización o comunicación.</p>
      <p>Específicamente, utilizamos MailChimp para almacenar direcciones de correo electrónico de quienes han optado por nuestras campañas de marketing por correo electrónico. También utilizamos MailChimp para distribuir correos electrónicos de marketing a nuestra lista de suscriptores. Estos correos electrónicos pueden contener un píxel o una baliza web que identifica si usted 1) recibió el correo electrónico; 2) abrió el correo electrónico; o 3) hizo clic en el correo electrónico. Puede optar por no recibir o cancelar la suscripción a nuestros correos electrónicos de marketing si no desea que recopilemos esta información sobre usted. También puede enviarnos un correo electrónico si desea que lo eliminemos. Para obtener más información, consulte<a href="http://mailchimp.com/legal/privacy/" rel="noreferrer" target="_blank">Mailchimp’s own Privacy Policy&#8203;</a>.</p>
      <h2>Online Advertising</h2>
      <p>Participamos en una variedad de publicidad en línea. Esta publicidad le muestra nuestros anuncios en los sitios web y aplicaciones que residen fuera de este sitio web.</p>
      <p>Recopilamos información que identifica:</p>
      <ul><li>qué anuncios se muestran</li>
        <li>en qué anuncios se hace clic  </li>
        <li>donde se mostró el anuncio</li></ul>
      <h3>Botones, herramientas y contenido de otras empresas</h3>
      <p>Nuestros sitios web pueden incluir funciones como complementos, botones, herramientas o contenido que enlazan con otras empresas. Podemos recopilar información sobre su uso de estas funciones. Además, cuando ve o interactúa con estos botones, herramientas o contenido, o ve cualquiera de nuestras páginas web que los contienen, cierta información de su navegador puede enviarse automáticamente a la otra empresa. Lea la política de privacidad de esa empresa para obtener más información.</p>
      <h3>Social Media</h3>
      <p>Tenemos presencia en diversas redes sociales, como Facebook, Instagram, Twitter, Google+, Pinterest y LinkedIn. Podemos recopilar información cuando interactúa con nuestras cuentas y páginas de redes sociales.</p>
      <h2>III. CÓMO UTILIZAMOS Y COMPARTIMOS LA INFORMACIÓN</h2>
      <p>Los datos que recopilamos sobre usted pueden usarse de las siguientes maneras:</p>
      <ul><li>Solución de problemas de nuestros sitios web y diagnóstico de problemas</li>
        <li>Proporcionarle cualquier servicio, soporte o información que haya solicitado.</li>
        <li>Comprender mejor el comportamiento del usuario en nuestros sitios para que podamos actualizar nuestro sitio web para satisfacer mejor las necesidades e intereses de nuestros clientes. </li>
        <li>Enviarle información sobre nuestra Compañía o nuestro sitio web</li>
        <li>Enviar mensajes a clientes de nuestra Compañía que pertenecen a diversas funciones comerciales, como aquellas relacionadas con pagos o cambios en el servicio.</li>
        <li>Reducir y abordar casos de fraude y protegerlo a usted y a la Compañía</li></ul>
      <h3>Informacion personal:</h3>
      <p>En general, no vendemos, comercializamos, alquilamos ni compartimos de otro modo su información personal con terceros sin su consentimiento. Podemos compartir su Información personal con proveedores y otros proveedores externos que prestan servicios para la Compañía. En general, los vendedores y proveedores externos que utilizamos solo recopilarán, usarán y divulgarán su información en la medida necesaria para permitirles realizar los servicios que brindan a la Compañía. Por ejemplo, cuando nos proporciona información personal para completar una transacción, verificar su tarjeta de crédito, realizar un pedido, concertar una entrega o devolver una compra, acepta que recopilemos y utilicemos dicha información personal para ese propósito específico, incluido transmitiendo dicha información a nuestros proveedores (y sus proveedores de servicios) que realizan estos servicios para la Compañía.  </p>
      <p>Sin embargo, ciertos proveedores de servicios externos, como los procesadores de pagos, tienen sus propias políticas de privacidad con respecto a la información que debemos proporcionarles para utilizar sus servicios. Para estos proveedores de servicios externos, le recomendamos que lea sus políticas de privacidad para que pueda comprender la manera en que dichos proveedores manejarán su información personal.</p>
      <p>Además, podemos divulgar su información personal si así lo exige la ley o si viola nuestros Términos de uso.</p>
      <h3>Información no personal:</h3>
      <p>En general, utilizamos información no personal para ayudarnos a mejorar el sitio web y personalizar la experiencia del usuario. También agregamos información no personal para rastrear tendencias y analizar patrones de uso del sitio web. Esta Política de Privacidad no limita de ninguna manera nuestro uso o divulgación de Información No Personal y nos reservamos el derecho de usar y divulgar dicha Información No Personal a nuestros socios, anunciantes y otros terceros a nuestro exclusivo criterio.</p>
      <h2>IV. CÓMO PROTEGEMOS LA INFORMACIÓN</h2>
      <p>Implementamos precauciones razonables y seguimos las mejores prácticas de la industria para proteger su Información personal y garantizar que no se acceda a dicha Información personal, no se divulgue, se altere ni se destruya. Sin embargo, estas medidas no garantizan que no se accederá, divulgará, alterará o destruirá su información por incumplimiento de dichas precauciones. Al utilizar nuestro sitio web, usted reconoce que comprende y acepta asumir estos riesgos.</p>
      <h2>V.SUS DERECHOS CON RESPECTO AL USO DE SU INFORMACIÓN PERSONAL</h2>
      <p>Puede optar por restringir la recopilación o el uso de su información personal de las siguientes maneras:</p>
      <ul><li>Siempre que se le solicite completar un formulario en el sitio web, busque la casilla en la que puede hacer clic para indicar que desea que la información se utilice con fines de marketing directo y déjela sin marcar.</li>
        <li>Si previamente aceptó que utilicemos su información personal con fines de marketing directo, puede cambiar de opinión en cualquier momento escribiéndonos o enviándonos un correo electrónico.</li></ul>
      <p>No venderemos, distribuiremos ni cederemos su información personal a terceros a menos que tengamos su permiso o la ley nos exija hacerlo.</p>
      <p>Si cree que la información que tenemos sobre usted es incorrecta o está incompleta, escríbanos o envíenos un correo electrónico lo antes posible a la dirección anterior. Corregiremos de inmediato cualquier información que se considere incorrecta.</p>
      <h2>VI. ALOJAMIENTO</h2>
      <p>Nuestro sitio web está alojado por InMotion Hosting, Inc. InMotion Hosting nos proporciona la plataforma en línea que nos permite ofrecerle el sitio web. Su información, incluida la información personal, puede almacenarse a través de los servidores de InMotion Hosting. Al utilizar el sitio web, usted acepta la recopilación, divulgación, almacenamiento y uso de su información personal por parte de InMotion Hosting de acuerdo con la política de privacidad de InMotion Hosting.  </p>
      <h2>VII. ENLACES A OTROS SITIOS WEB</h2>
      <p>Como parte del sitio web, podemos proporcionar enlaces o compatibilidad con otros sitios web o aplicaciones. Sin embargo, no somos responsables de las prácticas de privacidad empleadas por esos sitios web ni de la información o el contenido que contienen. Esta Política de Privacidad se aplica únicamente a la información recopilada por nosotros a través del sitio web. Por lo tanto, esta Política de Privacidad no se aplica al uso que usted haga de un sitio web de terceros al que se accede seleccionando un enlace a través de nuestro sitio web. En la medida en que acceda o utilice el sitio web a través de otro sitio web o aplicación, la política de privacidad de ese otro sitio web o aplicación se aplicará a su acceso o uso de ese sitio o aplicación. Alentamos a nuestros usuarios a leer las declaraciones de privacidad de otros sitios web antes de proceder a utilizarlos.</p>
      <h2>VIII. CAMBIOS A NUESTRA POLÍTICA DE PRIVACIDAD</h2>
      <p>La Compañía se reserva el derecho de cambiar esta Política de Privacidad y nuestros Términos de Uso en cualquier momento. Si decidimos cambiar esta Política de Privacidad, publicaremos estos cambios en esta página para que siempre esté al tanto de qué información recopilamos, cómo la usamos y bajo qué circunstancias la divulgamos. Cualquier modificación de este tipo entrará en vigor tras su acceso continuo y/o uso del sitio web cinco (5) días después de que publiquemos por primera vez los cambios en el sitio web o le proporcionemos un aviso de dichas modificaciones. Es su exclusiva responsabilidad consultar este sitio web de vez en cuando para ver dichos cambios en los términos de esta Política de Privacidad. Si no está de acuerdo con algún cambio, siempre y cuando dichos cambios puedan realizarse en esta Política de Privacidad, debe dejar de acceder a este sitio web. Si nos ha proporcionado su dirección de correo electrónico, nos da permiso para enviarle un correo electrónico con el fin de notificarle como se describe en esta Política de Privacidad.</p>
      <h2>IX. FUSIÓN O ADQUISICIÓN</h2>
      <p>En caso de que realicemos una transacción comercial como una fusión, adquisición por parte de otra empresa o venta de todos o parte de nuestros activos, su información personal puede estar entre los activos transferidos. Usted reconoce y acepta que dichas transferencias pueden ocurrir y están permitidas por esta Política de Privacidad, y que cualquier adquirente de nuestros activos puede continuar procesando su Información Personal como se establece en esta Política de Privacidad. Si nuestras prácticas de información cambian en algún momento en el futuro, publicaremos los cambios de política aquí para que usted pueda optar por no participar en las nuevas prácticas de información. Le sugerimos que consulte esta Política de Privacidad periódicamente si le preocupa cómo se utiliza su información. </p>
      <h2>X. CONTÁCTENOS Y RETIRAR EL CONSENTIMIENTO</h2>
      <p>Si tiene alguna pregunta sobre esta Política de Privacidad o las prácticas de este Sitio, o desea retirar su consentimiento para la recopilación, el uso o la divulgación continua de su Información personal, comuníquese con nosotros enviándonos un correo electrónico.</p>
      <h2>XI. Última actualización</h2>
      <p>Esta Política de Privacidad se actualizó por última vez el viernes 1 de diciembre de 2023.</p>

    </div>
  )
}

export default Policy
